### ISSUE TITLE
Crear la configuracion para la conexion a base de datos

### ISSUE THREAD

**Issue by dsanch3z** [Nixabud/Docauto#4]
# TO-DO
- [x] Se necesita agregar la dependencia de spring-jpa al archivo pm.xml:
  `<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-jpa</artifactId>
  </dependency>`
- [x] Se necesitan agregar las configuraciones al archivo application.yml: [Spring Boot Apendix](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
- [x] En el caso de Oracle DB se requiere agregar manualmente a maven usando:
  `mvn install:install-file
  -Dfile=path/de/archivo/jar.jar
  -DgroupId=com.oracle 
  -DartifactId=ojdbc6
  -Dversion=11.2.0
  -Dpackaging=jar`

**Comment by Nixabud** [comment]
Del segundo punto que configuraciones hay que agregar?, ya jale el archivo .yml al proyecto con el que estamos trabajando solo me falta esta parte para pasar el jsp del siguiente issue

**Comment by dsanch3z** [comment]
Me parece que solo con estas:
Y me queda duda en la de database-plataform no se si solo vaya "oracle"
spring.data.jpa.repositories.enabled=true
spring.jpa.database-platform=
spring.jpa.show-sql=true

**Comment by dsanch3z** [comment]
## Propiedades para conectar con BD

Solo hay que confirmar el url_db para conectarse con la base y el driverClassName checar que sea el mismo que la version del jar.

> spring.jpa.hibernate.ddl-auto=update
> spring.jpa.database=oracle
> 
> spring.datasource.platform=oracle
> spring.datasource.url=jdbc:oracle:thin:@<url_db>
> spring.datasource.username=
> spring.datasource.password=
> spring.datasource.driverClassName=oracle.jdbc.OracleDriver
> spring.datasource.initialize=false
